La til *.iml i gitignore, så det ikkje blir med, i versjonskontrollen.
navikt/syfoalerts pull request #6
Opened 2019-05-29 08:45 UTC by MikAoJk

Oppdaterte readme, med informasjon ang repoet.
La til alert på appen syfotekster

2019-05-29 08:47 UTC, knutnyg commented
Burde den også legges til i `syfo-app-nede`?

2019-05-29 08:58 UTC, MikAoJk commented
> Burde den også legges til i `syfo-app-nede`?

Jepp, ifix

2019-05-29 11:53 UTC, tiafiring approved these changes

2019-05-29 11:55 UTC, tiafiring requested changes
Jeg vil også gjerne ha denne inn i syfo-app-nede, men får ikke revoket approven min :P

2019-05-31 06:34 UTC, tiafiring approved these changes
Skikkelig bra å få dette på plass! 🏆

2019-05-31 06:49 UTC, merged